# Generated by Django 3.2 on 2021-04-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursechapter',
            table='course_chapter',
        ),
        migrations.AlterModelTable(
            name='courselesson',
            table='course_lesson',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
