# Generated by Django 3.2 on 2021-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210415_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '收费课程'), (1, '高级课程'), (2, '专业技能'), (3, '限时免费')], default=0, verbose_name='付费类型'),
        ),
    ]
