# Generated by Django 3.2 on 2021-04-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_course_video_courselesson_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='Lesson_video',
            new_name='lesson_video',
        ),
    ]
