# Generated by Django 3.2 on 2021-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210420_2120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='coursediscount',
            table='course_discount',
        ),
        migrations.AlterModelTable(
            name='coursediscounttype',
            table='course_discount_type',
        ),
        migrations.AlterModelTable(
            name='courseexpire',
            table='course_expire',
        ),
        migrations.AlterModelTable(
            name='coursepricediscount',
            table='course_price_discount',
        ),
    ]
